#!/usr/bin/env python
# Extract the make, model, and serial number from the output of smartctl and
#  return it as a single-line string.
#
# It is expected that the input of this script is the output of the following
#  command:
#   $ smartctl -i /dev/<drive>
#
# Author: Doug McGeehan <djmvfb@mst.edu>
#

import sys

MAKE_KEY = "Model Family"
MODEL_KEY = "Device Model"
SERIAL_KEY = "Serial Number"
hard_drive_info = {
    MAKE_KEY: '',
    MODEL_KEY: '',
    SERIAL_KEY: ''
}

# See here for more information:
#   https://en.wikipedia.org/wiki/GUID_Partition_Table#Partition_entries
MAX_GPT_PARTITION_NAME_LENGTH = 36

for line in sys.stdin:
    line_parts = line.strip().split(':')
    if len(line_parts) > 1 and line_parts[0] in hard_drive_info.keys():
        hard_drive_info[line_parts[0]] = line_parts[1].strip()

# Remove trailing bits from model name.
hard_drive_info[MODEL_KEY] = hard_drive_info[MODEL_KEY].split()[0]
output = "{model}.{serial}".format(
    model=hard_drive_info[MODEL_KEY],
    serial=hard_drive_info[SERIAL_KEY]
)
assert len(output) <= MAX_GPT_PARTITION_NAME_LENGTH, "'{}' is too long!".format(output)    
print(output)
